# Your Website Title
title: Nuestra Boda ğŸ’

# Your Website URL
url: https://nuestra-boda.github.io/

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: NUESTRA BODA ğŸ’
tagline: "SI NO RECUERDAS LA LOCURA EN LA QUE EL AMOR TE HIZO CAER ES QUE NO HAS AMADO" â¤
pic: 
description: ENCUENTRA INFORMACIÃ“N SOBRE EL GRAN DÃA 
description_tiny: AMOR+AMOR=FELICIDAD ğŸ’‘
email: nuestrabodaeym@gmail.com
website: nuestra-boda.github.io
github: Nuestra-Boda
twitter: @nuestrabodaeym
